---
run:
    # mochi in not written with generics (a.t.m),
    # so we can check with 1.17
    go: "1.17"
    timeout: "5m"
output:
    sort-results: true
linters-settings:
    goimports:
        local-prefixes: "sot-te.ch/mochi"
    staticcheck:
        checks:
            - "all"
    gosec:
        excludes:
            - "G404"  # Allow the usage of math/rand
            - "G505"  # Allow SHA1 usage
linters:
    enable:
        - "bidichk"
        - "bodyclose"
        - "errcheck"
        - "errname"
        - "errorlint"
        - "gofumpt"
        - "goimports"
        - "goprintffuncname"
        - "gosec"
        - "gosimple"
        - "govet"
        - "importas"
        - "ineffassign"
        - "makezero"
        - "prealloc"
        - "predeclared"
        - "revive"
        - "rowserrcheck"
        - "staticcheck"
        - "stylecheck"
        - "tenv"
        - "typecheck"
        - "unconvert"
        - "unused"
        - "wastedassign"
        - "whitespace"
issues:
    include:
        - "EXC0012"  # Exported should have comment
        - "EXC0012"  # Exported should have comment
        - "EXC0013"  # Package comment should be of form
        - "EXC0014"  # Comment on exported should be of form
        - "EXC0015"  # Should have a package comment
