---
name: "Lint"
on:
    push:
        branches:
            - "!dependabot/*"
            - "master"
    pull_request:
        branches: [ "*" ]
jobs:
    go-lint:
        name: "Lint Go"
        runs-on: "ubuntu-latest"
        steps:
            -   uses: "actions/checkout@v3"
            -   uses: "actions/setup-go@v3"
                with:
                    go-version: "^1.18"
            -   uses: "authzed/actions/gofumpt@main"
            -   uses: "authzed/actions/go-mod-tidy@main"
            -   uses: "authzed/actions/go-generate@main"
            -   uses: "authzed/actions/golangci-lint@main"
    
    codeql:
        name: "Analyze with CodeQL"
        runs-on: "ubuntu-latest"
        permissions:
            actions: "read"
            contents: "read"
            security-events: "write"
        strategy:
            fail-fast: false
            matrix:
                language: [ "go" ]
        steps:
            -   uses: "actions/checkout@v3"
            -   uses: "authzed/actions/codeql@main"